### ISSUE TITLE
path to the USB device should not be hardcoded

### ISSUE THREAD

**Issue by proppy** [efabless/caravel_board#18]
currently path the usb device is hardcoded in https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/Makefile#L5 which seems to use a path specific to a macosx installation.

On Linux based operating system, the path is likely to be different (`/dev/ttyACM0`, `/dev/ttyUSB0`) so something that detect the nucleo board is probably desirable:
```
(env) nucleo 👹 mpremote connect list
/dev/ttyACM0 066AFF495087534867055928 0483:374b STMicroelectronics STM32 STLink
/dev/ttyS0 None 0000:0000 None None
```

**Comment by proppy** [comment]
That's also true of the mount path in https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/Makefile#L9.

As a reference here is what I change to in order to reference the right devices on GNU/Linux:
https://github.com/proppy/caravel_board/commit/a113f39025f0b480152abd282bf8da47106492d5

**Comment by proppy** [comment]
duplicate of #10?

**Comment by jeffdi** [comment]
This has been updated to automatically set the path (v1.2.0).
