### ISSUE TITLE
ValueError: incompatible .mpy file

### ISSUE THREAD

**Issue by ayushman22git** [efabless/caravel_board#20]
Getting the following error when do make run. 
ayushman_ubuntu@UbuntuLTS:~/caravel_board/firmware_vex/nucleo$ make run
mpremote connect /dev/ttyACM0  exec "import machine; machine.reset()"
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "io_config.py", line 1, in <module>
  File "nucleo_api.py", line 3, in <module>
ValueError: incompatible .mpy file
MicroPython v1.19.1-616-g5987130af-dirty on 2022-11-20; NUCLEO-F746ZG with STM32F746

Type "help()" for more information.

@msaligane

**Comment by proppy** [comment]
Maybe an outdated version of the mpy files on the device?

Did you try:
```
mpremote ls
```

**Comment by ayushman22git** [comment]
> 
This is the response I get with mpremote ls

<img width="339" alt="image" src="https://user-images.githubusercontent.com/121267341/213050088-fb4545d8-e47b-4d62-85e7-a4000022e5c3.png">

**Comment by proppy** [comment]
@ayushman22git can you give more details on how you connected the board to the host computer?

**Comment by proppy** [comment]
@ayushman22git did you also run:
```
make compile
make copy
```

**Comment by ayushman22git** [comment]
@proppy I connected using the CN1 connector on Nucleo to my USB host. Utilized mpremote. I had not run these 2 commands. However I have now run these commands. the following is the output 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/121267341/213088473-8019c01e-21fc-4e11-8f6e-0edbaa458de3.png">
Copy is not proceeding beyond this point. However, after several iterations the copy operation halted as in figure 2. 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/121267341/213089409-d765f8ce-c4ae-42b2-bfac-d4226984305f.png">
Not proceeding  beyond this point.  When interrupt this at times I see mostly the following output. It seems to hang. In some trials, see earlier error message with make run as well. 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/121267341/213089958-599c86e8-bc33-4d04-a7b4-3918148e2d22.png">

**Comment by proppy** [comment]
another possible workaround is not not compile mpy file and simply copy py file around:
https://github.com/proppy/caravel_board/commit/d19877f864fbc368b3874f8979909bdc99b4f162

**Comment by proppy** [comment]
@ayushman22git one gotcha that @mattvenn figured out during his recent demonstration, is that a more reliable copy is possible by:
- reflashing the board with `make F746ZG`
- connecting another usb cable on the opposite side of the st-link connector
- mounting the corresponding volume that's showing up
- updating the path to the volume in https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/Makefile#L9
- copying the file using `make copy2`
-

**Comment by jeffdi** [comment]
proppry instrustuctions are correct and are now included to the README
