### ISSUE TITLE
all possible led blinking patterns should be correctly documented

### ISSUE THREAD

**Issue by proppy** [efabless/caravel_board#26]
Looking at the test being performed there seems to be  multiple possible results of the GPIO characterization

| ID            | LOW    | HIGH    |
|--------------|----------|-------------|
| A | PASS | PASS |
| B | PASS | PARTIAL |
| C | PASS | FAIL |
| D | PARTIAL | PASS |
| E | PARTIAL | PARTIAL |
| F | PARTIAL | FAIL |
| G | FAIL | PASS | 
| H | FAIL | PARTIAL | 
| I | FAIL | FAIL |

Looking at https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/README.md?plain=1#L62-L66 it seems that only 3 patterns are documented: A, (B or C), (D or G)

| ID            | LOW    | HIGH    | GREEN | RED  | 
|--------------|----------|-------------|------|-------------|
| A              | PASS | PASS | 2 short + 4 long | off | 
| B or C | PASS | PARTIAL or  FAIL | 2 short | 2 long | 
| D or G| PARTIAL or FAIL | PASS| 2 short | 4 long | 

And looking at https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/io_config.py#L354-L362 it seems that only 3 blinking modes are actually implemented with different patterns than the one documented:

| ID            | LOW    | HIGH    | GREEN | RED  | 
|--------------|----------|-------------|------|-------------|
| A              | PASS | PASS | 2 short + 4 long | off | 
| B or C | PASS | PARTIAL or  FAIL | 2 long | 2 short | 
| D or E or F oe G or H or I| PARTIAL or FAIL | PASS or PARTIAL or FAIL| 4 long | 2 short |

**Comment by jeffdi** [comment]
the documentation has been updated for all test completion led patterns.  additional patterns added to cover missing cases.
