### ISSUE TITLE
io_config control should give back control to the micropython interpreter

### ISSUE THREAD

**Issue by proppy** [efabless/caravel_board#27]
currently the `io_config` test finish by a busy loop to blink the onboard LED in order to convey the status to the user:
https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/io_config.py#L354-L362

It would be nice to rely instead on timer (if available on the nucleo port): https://docs.micropython.org/en/latest/pyboard/tutorial/timer.html?highlight=timer so that you can give control back to the main interpreter (without requiring the user to interrupt the script).

**Comment by jeffdi** [comment]
added Ctl-C statement to prompt users
