### ISSUE TITLE
GPIO0 missing

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/caravel_board#30]
The io_config.py doesn't check for GPIO#0 , it starts with GPIO#1:
```
*** flashing Caravel
gpio[1] >> Passed
```
but in the end it claims that gpio#0 is ok:
`
== LOW chain FAILED.   Valid IO = 0 thur 14.                      ==
`

**Comment by thesourcerer8** [comment]
It also claims that GPIOs are valid which have actually timed out!

**Comment by thesourcerer8** [comment]
These are off-by-one errors.

**Comment by proppy** [comment]
Is that fixed by @jeffdi's recent commit?
https://github.com/efabless/caravel_board/commits?author=jeffdi

**Comment by thesourcerer8** [comment]
I heard from Tim Edwards, that the GPIO0 does not have any Hold Violations, so it's assumed to be always good and doesn't need to be checked.
