### ISSUE TITLE
There's no clear starting place to get going with the board

### ISSUE THREAD

**Issue by QuantamHD** [efabless/caravel_board#5]
There should be a single page where users can go that says do X, Y, and Z. The video shared doesn't show any of the setup.

https://www.youtube.com/watch?v=76hmGHJMyYs

**Comment by jeffdi** [comment]
Please see https://github.com/efabless/caravel_board/blob/main/firmware_vex/nucleo/README.md

Does this provide what is needed?

**Comment by mguthaus** [comment]
Can we add a "hello world" to this such as blinking an LED with micropython?

**Comment by jeffdi** [comment]
created a ticket for the hello world request.  please create a new issue if there is still missing info.
