### ISSUE TITLE
add 5V support for GFMPW-0 for caravel development board and nucleo hat

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel_board#75]
Add support for 5V to Caravel all supplies to support GF180.  The priority is Caravel Development Board followed by the Hat.

The design should allow the user to switch between 1.8/3.3V and 5V so that the same board can be used for either SKY130 or GF180.

**Comment by jeffdi** [comment]
Yes - a jumper would be good.

-- Jeff

**Comment by DavidRLindley** [comment]
Yes, it is completed by [PR#78](https://github.com/efabless/caravel_board/pull/78) but we decided to separate GF180 5V boards from sky130 3.3V boards. 5V boards V6 could be found [here](https://github.com/efabless/caravel_board/tree/main/hardware/development/caravel-dev-gf180-v6-M.2)
